In [12]:
from sklearn import tree
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.ensemble import GradientBoostingRegressor
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd

In [13]:
df = pd.read_csv("db/results_and_goals.csv",parse_dates=True).dropna().drop("meet_date",axis=1).drop("gender",axis=1)

In [14]:
df.head()

,id,runr_id,school_id,race_result,pr_time,previous_time,last_year_time,improvement_flag,pr_flag,goal_time,pg_flag,course_id,distance,grade_number,run_before
0,305,3038,834,99600,103500,103500,103500,1,1,96000.0,0.0,3,310,1,1
1,357,3050,834,109300,109300,0,0,0,0,107900.0,0.0,98,310,1,0
2,363,3050,834,104100,105600,105600,105600,1,1,101000.0,0.0,205,308,1,1
3,493,3751,895,76200,81500,81500,0,1,1,78000.0,0.0,11,200,1,1
4,494,3751,895,78470,81040,81040,81040,1,1,78000.0,0.0,123,200,1,1

In [15]:
X = df.drop("race_result",axis=1)

In [16]:
y=df["race_result"]

In [26]:
df.reset_index()

,index,id,runr_id,school_id,race_result,pr_time,previous_time,last_year_time,improvement_flag,pr_flag,goal_time,pg_flag,course_id,distance,grade_number,run_before
0,0,305,3038,834,99600,103500,103500,103500,1,1,96000.0,0.0,3,310,1,1
1,1,357,3050,834,109300,109300,0,0,0,0,107900.0,0.0,98,310,1,0
2,2,363,3050,834,104100,105600,105600,105600,1,1,101000.0,0.0,205,308,1,1
3,3,493,3751,895,76200,81500,81500,0,1,1,78000.0,0.0,11,200,1,1
4,4,494,3751,895,78470,81040,81040,81040,1,1,78000.0,0.0,123,200,1,1
5,5,499,3751,895,116413,118100,118100,0,1,1,114000.0,0.0,512,300,1,1
6,6,500,3829,895,68400,79030,79030,0,1,1,72000.0,0.0,11,200,1,1
7,7,501,3829,895,102900,113700,113700,0,1,1,105000.0,0.0,44,293,1,1
8,8,502,3829,895,70660,75900,75900,75900,1,1,72000.0,0.0,123,200,1,1
9,9,505,3829,895,74275,79900,79900,0,1,1,80000.0,0.0,137,200,1,1
10,10,528,3853,895,112000,110234,116348,116348,1,0,114000.0,0.0,136,295,1,1
11,11,543,4152,896,64970,65430,67600,65430,1,1,64000.0,0.0,123,200,1,1
12,12,552,4162,896,73430,72720,75500,73590,1,0,71000.0,0.0,123,200,1,1
13,13,553,4162,896,68110,72720,73430,72720,1,1,68800.0,0.0,123,200,1,1
14,14,585,4181,896,94000,95200,95200,95200,1,1,92900.0,0.0,3,310,1,1
15,15,593,4185,896,127200,114900,114900,126300,0,0,119000.0,0.0,9,310,1,1
16,16,597,4185,896,82390,80690,86100,85440,1,0,83000.0,0.0,123,200,1,1
17,17,767,5380,907,118100,124200,124200,0,1,1,118000.0,0.0,3,310,1,1
18,18,774,5380,907,113100,118500,118500,118500,1,1,114000.0,0.0,25,280,1,1
19,19,775,5380,907,117700,117700,0,0,0,0,112500.0,0.0,80,293,1,0
20,20,784,5393,907,106600,106600,0,0,0,0,104000.0,0.0,3,310,1,0
21,21,788,5393,907,83100,83100,0,0,0,0,83000.0,0.0,14,240,1,0
22,22,789,5393,907,99000,109900,109900,0,1,1,98000.0,0.0,25,280,1,1
23,23,790,5393,907,103400,103400,0,0,0,0,96000.0,0.0,80,293,1,0
24,24,791,5393,907,72710,77110,77110,0,1,1,70000.0,0.0,123,200,1,1
25,25,794,5416,908,94800,95200,97600,95200,1,1,92000.0,0.0,44,293,1,1
26,26,800,5416,908,94819,97378,97378,97378,1,1,93000.0,0.0,265,300,1,1
27,27,933,5707,912,105500,104600,104900,104900,0,0,102000.0,0.0,281,295,1,1
28,28,934,5707,912,62640,63800,64390,64390,1,1,60000.0,0.0,284,200,1,1
29,29,936,5732,912,82900,84200,84200,84200,1,1,75000.0,0.0,226,215,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24842,24842,503558,171599,959,131800,127500,127500,0,0,0,120000.0,1.0,5,295,4,1
24843,24843,503559,171599,959,98900,98900,0,0,0,0,117000.0,1.0,37,233,4,0
24844,24844,503560,171599,959,115120,115120,0,0,0,0,90000.0,1.0,81,213,4,0
24845,24845,503561,171599,959,100800,100800,0,0,0,0,102000.0,1.0,1576,240,4,0
24846,24846,503562,171599,959,115000,115000,0,0,0,0,102000.0,1.0,1593,250,4,0
24847,24847,510798,173533,959,164500,161900,161900,0,0,0,150000.0,1.0,5,295,1,1
24848,24848,510799,173533,959,172900,161900,164500,0,0,0,165000.0,1.0,5,295,1,1
24849,24849,510800,173533,959,126200,126200,0,0,0,0,114000.0,1.0,37,233,1,0
24850,24850,510801,173533,959,126600,126600,0,0,0,0,114000.0,1.0,1576,240,1,0
24851,24851,510802,173533,959,137600,137600,0,0,0,0,150000.0,1.0,1593,250,1,0
24852,24852,511414,173707,839,91100,91100,0,0,0,0,90000.0,1.0,1576,240,4,0
24853,24853,511422,173711,839,92300,92300,0,0,0,0,90800.0,1.0,1576,240,4,0
24854,24854,511434,173714,839,127800,127800,0,0,0,0,114400.0,1.0,1576,240,4,0
24855,24855,511555,173735,839,97500,97500,0,0,0,0,108000.0,1.0,1576,240,4,0
24856,24856,511601,173742,839,91000,91000,0,0,0,0,90000.0,1.0,1576,240,4,0
24857,24857,511694,173759,839,84000,84000,0,0,0,0,84500.0,1.0,1576,240,4,0
24858,24858,511704,173762,839,101100,101100,0,0,0,0,42000.0,1.0,1576,240,4,0
24859,24859,511718,173764,839,79300,79300,0,0,0,0,79000.0,1.0,1576,240,4,0
24860,24860,511740,173767,839,90400,90400,0,0,0,0,66000.0,1.0,1576,240,4,0
24861,24861,511748,173768,839,87200,87200,0,0,0,0,38700.0,1.0,1576,240,4,0
24862,24862,511754,173769,839,109100,109100,0,0,0,0,108000.0,1.0,1576,240,4,0
24863,24863,515325,174879,839,90400,90400,0,0,0,0,87000.0,1.0,1576,240,4,0
24864,24864,515693,174963,1174,136762,136762,0,0,0,0,142000.0,1.0,47,300,4,0
24865,24865,515694,174963,1174,142680,142680,0,0,0,0,141000.0,1.0,1119,300,4,0
24866,24866,515695,174963,1174,136680,142680,142680,0,1,1,136500.0,1.0,1119,300,4,1
24867,24867,515698,174963,1174,142420,142420,0,0,0,0,141000.0,1.0,1457,300,4,0
24868,24868,519873,177183,839,115700,115700,0,0,0,0,111000.0,1.0,1576,240,2,0
24869,24869,574752,230840,1228,153300,153300,0,0,0,0,150000.0,1.0,438,297,4,0
24870,24870,575614,231007,1228,165900,165900,0,0,0,0,144000.0,1.0,438,297,4,0
24871,24871,576675,231590,1228,165500,165500,0,0,0,0,162000.0,1.0,438,297,4,0

In [17]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=78)

In [18]:
scaler = StandardScaler()
X_scaler = scaler.fit(X_train)
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

C:\Users\dawnb\Anaconda3\lib\site-packages\sklearn\preprocessing\data.py:645: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
C:\Users\dawnb\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\dawnb\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  after removing the cwd from sys.path.

In [19]:
model = GradientBoostingRegressor(
    n_estimators=500,
    learning_rate=.25,
    max_features=5,
    max_depth=3,
    random_state=0)
# Fit the model
model.fit(X_train_scaled,y_train.ravel())
# Score the model
print("Accuracy score (training): {0:.3f}".format(
    model.score(
        X_train_scaled,
        y_train)))
print("Accuracy score (validation): {0:.3f}".format(
    model.score(
        X_test_scaled,
        y_test)))

Accuracy score (training): 0.989
Accuracy score (validation): 0.978

In [20]:
predictions = model.predict(X_test_scaled)
y_test = y_test.ravel()
actual = pd.Series(y_test)

In [21]:
pd.DataFrame({'Model0':predictions,'Actual': actual}).head()

          Model0  Actual
0   91964.616329   92900
1  124206.103454  124480
2  143447.200678  143830
3   96685.326256   92830
4   76795.451121   74020

In [ ]:
df.

In [22]:
fold_importance_df=pd.DataFrame()
fold_importance_df['Feature']=df.tail(5).columns
feature_importance_df=pd.DataFrame()
fold_importance_df["importance"]=model.feature_importances_[:len(df.tail(5).columns)]
feature_importance_df=pd.concat([feature_importance_df, fold_importance_df], axis=0)
cols = (feature_importance_df[["Feature", "importance"]]
        .groupby("Feature")
        .mean()
        .sort_values(by="importance", ascending=False)[:200].index)
best_features = feature_importance_df.loc[feature_importance_df.Feature.isin(cols)]
plt.figure(figsize=(10,10))
sns.barplot(x="importance", y="Feature", data=best_features.sort_values(by="importance",ascending=False))
plt.title('LightGBM Features (averaged over folds)')
plt.tight_layout()
plt.savefig('lgbm_importances.png')

ValueError: Length of values does not match length of index